//line abstime.w:34
package main

import (
	"fmt"
	"os"
	"time"
)

func main() {
	pkg := "main"
	if len(os.Args) > 1 {
		pkg = os.Args[1]
	}
	fmt.Printf("// Code generated by abstime; DO NOT EDIT.\n\n")
	fmt.Printf("package %s\n\nconst ABSTIME = %d\n", pkg, time.Now().Unix())
}
