% 이 파일은 MMIXware의 abstime.w((c) 1999 Donald E. Knuth)를 한글 GWEB(Go)로
% 옮긴 것으로, MMIXware 꾸러미의 일부가 아니다.
@i ../boilerplate.w

\input kotexgweb
\def\title{ABSTIME}

@* 들어가며. 이 작은 프로그램은 그리니치 평균시로 1970년 1월 1일 00:00:00부터 지금까지
흐른 초의 수를 찍는다. (그리니치 평균시는 지금은 협정 세계시, 곧 UTC라고 부르는 것이
더 알맞다.)

2038년 1월 19일 03:14:08 UTC가 되면, 부호 있는 32비트 정수로는 이 결과를 담을 수 없게
된다. (그때 흐른 초의 수가 $2^{31}$이 된다.) 이 프로그램을 \KW{time\_t}가 \KW{long}과 같은
타입인 \CEE/ 컴파일러로 컴파일했다면, 그리고 \KW{long} 정수가 32비트보다 크다면, 이
프로그램은 그해 1월 20일에도 여전히 동작할 것이다.

보충: \GO/의 |time.Now().Unix()|는 |int64|를 돌려주므로 이 걱정은 언어 수준에서
사라진다. 부호 있는 64비트 정수가 넘치는 것은 약 2920억 년 뒤의 일이다.

@ 이 수를 쓰는 곳은 두 \MMIX\ 시뮬레이터다. 두 시뮬레이터는 특수 레지스터 \.{rN}의
아래 32비트에 이 수를 넣어 시뮬레이터가 컴파일된 시각을 나타낸다. 그래서 \MMIX의 구현
하나하나가 저마다 다른 식별 번호를 가지게 된다. 원본은 결과를 \CEE/ 전처리기 매크로
`\.{\#define ABSTIME} \dots' 꼴로 찍었고, \.{Makefile}은 그것을 \.{abstime.h}라는 파일로 보내
시뮬레이터를 컴파일하기 직전에 끌어들였다. 시뮬레이터 쪽 주석이 경고하듯이, 이 수가
$2^{32}$보다 작다는 가정은 2106년 2월에 깨진다.

\GO/에는 전처리기가 없다. 그 대신 옮긴이의 판은 상수 |ABSTIME| 하나를 정의하는 완결된
\GO/ 소스 파일을 표준 출력에 찍는다. 시뮬레이터를 짓는 \.{Makefile}은 이것을 시뮬레이터
디렉터리의 \.{abstime.go}로 보낸다. 받는 쪽 패키지의 이름은 명령줄 인자로 주고, 주지
않으면 |main|이다. 첫 줄의 주석은 \GO/ 도구들이 ``생성된 파일''을 알아보는 표준 꼴이라서,
영어 문구 그대로 둔다.

@c
package main

import (
	"fmt"
	"os"
	"time"
)

func main() {
	pkg := "main"
	if len(os.Args) > 1 {
		pkg = os.Args[1]
	}
	fmt.Printf("// Code generated by abstime; DO NOT EDIT.\n\n")
	fmt.Printf("package %s\n\nconst ABSTIME = %d\n", pkg, time.Now().Unix())
}

@* 찾아보기.
